// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, expect, it, vi } from 'vitest'
import { ArtifactPreview, ArtifactPreviewEmpty } from './ArtifactPreview'
import type { Artifact } from '@/lib/artifacts'
const bridge = vi.hoisted(() => ({ readArtifact: vi.fn(), openArtifact: vi.fn(), saveArtifact: vi.fn() }))
vi.mock('@/lib/bridge', async original => ({ ...await original<typeof import('@/lib/bridge')>(), ...bridge }))
afterEach(() => { cleanup(); vi.resetAllMocks() })
const artifact: Artifact = { id: 'doc', name: 'report.md', kind: 'markdown', directory: '/workspace', path: 'report.md', source: 'reply', sourceId: 'message', createdAt: '' }
const picture: Artifact = { ...artifact, id: 'picture', name: '岛台 石材.JPG', path: '岛台 石材.JPG', kind: 'file' }
it('renders binary image previews, copies the path and preserves the last image on read failure', async () => {
  const writeText = vi.fn().mockResolvedValue(undefined)
  Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText } })
  bridge.readArtifact.mockResolvedValueOnce({ content: '', imageDataUrl: 'data:image/jpeg;base64,first' })
    .mockRejectedValueOnce(new Error('文件已删除'))
    .mockResolvedValueOnce({ content: '', imageDataUrl: 'data:image/jpeg;base64,updated' })
  render(<ArtifactPreview artifact={picture}/>)
  const img = await screen.findByRole('img', { name: picture.name })
  fireEvent.load(img)
  expect(img.className).toBe('is-ready')
  expect(screen.queryByRole('tab', { name: '源码' })).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: '复制文件路径' }))
  await waitFor(() => expect(writeText).toHaveBeenCalledWith('/workspace/岛台 石材.JPG'))
  fireEvent.click(screen.getByRole('button', { name: '刷新文件' }))
  expect((await screen.findByRole('alert')).textContent).toContain('刷新失败，仍显示上次读取的内容')
  expect(screen.getByRole('img', { name: picture.name })).toBe(img)
  fireEvent.click(screen.getByRole('button', { name: '重新读取' }))
  await waitFor(() => expect(screen.getByRole('img', { name: picture.name }).getAttribute('src')).toContain('updated'))
  expect(screen.queryByRole('alert')).toBeNull()
})
it('shows decode errors and does not let a stale image read replace a text document', async () => {
  let finish: (value: unknown) => void = () => {}
  bridge.readArtifact.mockResolvedValueOnce({ content: '', imageDataUrl: 'data:image/jpeg;base64,broken' })
    .mockImplementationOnce(() => new Promise(resolve => { finish = resolve }))
    .mockResolvedValueOnce({ content: '# Document' })
  const view = render(<ArtifactPreview artifact={picture}/>)
  fireEvent.error(await screen.findByRole('img', { name: picture.name }))
  expect(screen.getByRole('alert').textContent).toContain('图片无法解码')
  fireEvent.click(screen.getByRole('button', { name: '重新读取' }))
  view.rerender(<ArtifactPreview artifact={artifact}/>)
  await screen.findByRole('heading', { name: 'Document' })
  finish({ content: '', imageDataUrl: 'data:image/jpeg;base64,late' })
  await waitFor(() => expect(screen.queryByRole('img', { name: picture.name })).toBeNull())
  expect(screen.getByRole('tab', { name: '源码' })).toBeTruthy()
})
it('ignores stale reads when the user switches documents', async () => {
  let finish: (value: unknown) => void = () => {}
  bridge.readArtifact.mockImplementationOnce(() => new Promise(resolve => { finish = resolve })).mockResolvedValueOnce({ content: '# Second' })
  const props = { onClose: vi.fn(), onTrace: vi.fn() }
  const view = render(<ArtifactPreview artifact={artifact} {...props}/>)
  view.rerender(<ArtifactPreview artifact={{ ...artifact, id: 'second', path: 'second.md' }} {...props}/>)
  await screen.findByRole('heading', { name: 'Second' })
  finish({ content: '# Stale' })
  await waitFor(() => expect(screen.queryByRole('heading', { name: 'Stale' })).toBeNull())
})
it('allows retrying failed reads and preserves source for copy/save', async () => {
  bridge.readArtifact.mockRejectedValueOnce(new Error('文件不存在')).mockResolvedValueOnce({ content: '# Recovered' })
  render(<ArtifactPreview artifact={artifact}/>)
  expect((await screen.findByRole('alert')).textContent).toContain('文件不存在')
  fireEvent.click(screen.getByRole('button', { name: '重新读取' }))
  await screen.findByRole('heading', { name: 'Recovered' })
  fireEvent.click(screen.getByRole('button', { name: '系统打开' }))
  await waitFor(() => expect(bridge.openArtifact).toHaveBeenCalledWith('/workspace', 'report.md'))
})
it('previews inline HTML in an opaque sandbox and handles cancelled save', async () => {
  bridge.saveArtifact.mockResolvedValue(null)
  const content = '<h1>Preview</h1><script>alert(1)</script>'
  render(<ArtifactPreview artifact={{ ...artifact, path: undefined, kind: 'html', content }}/>)
  const frame = await screen.findByTitle('report.md HTML 预览')
  expect(frame.getAttribute('sandbox')).toBe('')
  expect(frame.getAttribute('srcdoc')).not.toContain('<script>')
  fireEvent.click(screen.getByRole('button', { name: '另存为' }))
  await waitFor(() => expect(bridge.saveArtifact).toHaveBeenCalledWith('report.md', content))
  expect(screen.queryByText('已保存文件')).toBeNull()
})
it('rereads the file, retains source mode, reports stale content on failure and recovers', async () => {
  let finish: (value: { content: string }) => void = () => {}
  bridge.readArtifact.mockResolvedValueOnce({ content:'# Original' })
    .mockImplementationOnce(() => new Promise(resolve => { finish = resolve }))
    .mockRejectedValueOnce(new Error('文件已删除'))
    .mockResolvedValueOnce({ content:'# Restored' })
  render(<ArtifactPreview artifact={artifact}/>)
  await screen.findByRole('heading', { name:'Original' })
  fireEvent.mouseDown(screen.getByRole('tab', { name:'源码' }), { button:0, ctrlKey:false })
  fireEvent.click(screen.getByRole('button', { name:'刷新文件' }))
  expect(screen.getByText('# Original')).toBeTruthy()
  expect((screen.getByRole('button', { name:'刷新文件' }) as HTMLButtonElement).disabled).toBe(true)
  finish({ content:'# Updated' })
  await screen.findByText('# Updated')
  expect(screen.getByRole('tab', { name:'源码' }).getAttribute('aria-selected')).toBe('true')
  expect(screen.getByRole('status').textContent).toContain('已刷新')
  fireEvent.click(screen.getByRole('button', { name:'刷新文件' }))
  expect((await screen.findByRole('alert')).textContent).toContain('刷新失败，仍显示上次读取的内容：文件已删除')
  expect(screen.getByText('# Updated')).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name:'重新读取' }))
  await screen.findByText('# Restored')
  expect(screen.queryByRole('alert')).toBeNull()
  expect(bridge.readArtifact).toHaveBeenCalledTimes(4)
  expect(bridge.readArtifact).toHaveBeenLastCalledWith('/workspace', 'report.md')
})

it('embeds remote pages only in an isolated frame, without reading local files', async () => {
  render(<ArtifactPreview artifact={{ ...artifact, path: undefined, url: 'https://example.com/report', kind: 'web', name: 'example.com' }}/>)
  const frame = await screen.findByTitle('example.com 网页预览')
  expect(frame.getAttribute('src')).toBe('https://example.com/report')
  expect(frame.getAttribute('sandbox')).toBe('allow-scripts allow-forms')
  expect(frame.getAttribute('referrerpolicy')).toBe('no-referrer')
  expect(bridge.readArtifact).not.toHaveBeenCalled()
  expect(screen.queryByRole('button', { name: 'Finder' })).toBeNull()
  expect(screen.queryByRole('button', { name: '另存为' })).toBeNull()
  expect(screen.getByText(/限制内嵌/)).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name: '刷新网页' }))
  expect(screen.getByTitle('example.com 网页预览')).not.toBe(frame)
})

it('supports following links inside a local Markdown preview', async () => {
  bridge.readArtifact.mockResolvedValue({ content: '[详情](./nested/report.html)' })
  const onOpenLink = vi.fn()
  render(<ArtifactPreview artifact={artifact} onOpenLink={onOpenLink}/>)
  fireEvent.click(await screen.findByRole('link', { name: '详情' }))
  expect(onOpenLink).toHaveBeenCalledWith('nested/report.html')
})

it('requires an explicit override above 500 MB and never carries it to another file', async () => {
  bridge.readArtifact.mockResolvedValueOnce({ content: '', bytes: 501 * 1024 * 1024, tooLarge: true })
    .mockResolvedValueOnce({ content: '# Large document', bytes: 501 * 1024 * 1024 })
    .mockResolvedValueOnce({ content: '', bytes: 502 * 1024 * 1024, tooLarge: true })
  const view = render(<ArtifactPreview artifact={artifact}/>)
  expect((await screen.findByRole('alert')).textContent).toContain('500 MB')
  expect(bridge.readArtifact).toHaveBeenLastCalledWith('/workspace', 'report.md')
  fireEvent.click(screen.getByRole('button', { name: '仍要打开' }))
  await screen.findByRole('heading', { name: 'Large document' })
  expect(bridge.readArtifact).toHaveBeenLastCalledWith('/workspace', 'report.md', true)
  expect(screen.queryByRole('button', { name: '仍要打开' })).toBeNull()
  view.rerender(<ArtifactPreview artifact={{ ...artifact, id: 'other-large', path: 'other.md' }}/>)
  await screen.findByRole('button', { name: '仍要打开' })
  expect(bridge.readArtifact).toHaveBeenLastCalledWith('/workspace', 'other.md')
  expect(screen.queryByRole('heading', { name: 'Large document' })).toBeNull()
})

it('keeps the large-file override for retries but still shows read errors', async () => {
  bridge.readArtifact.mockResolvedValueOnce({ content: '', bytes: 501 * 1024 * 1024, tooLarge: true })
    .mockRejectedValueOnce(new Error('读取文件失败'))
    .mockResolvedValueOnce({ content: '# Recovered large document' })
  render(<ArtifactPreview artifact={artifact}/>)
  fireEvent.click(await screen.findByRole('button', { name: '仍要打开' }))
  await screen.findByText('读取文件失败')
  fireEvent.click(screen.getByRole('button', { name: '重新读取' }))
  await screen.findByRole('heading', { name: 'Recovered large document' })
  expect(bridge.readArtifact).toHaveBeenLastCalledWith('/workspace', 'report.md', true)
})

it('clears an old preview when a refreshed file has grown beyond the automatic limit', async () => {
  bridge.readArtifact.mockResolvedValueOnce({ content: '# Original small document', bytes: 32 })
    .mockResolvedValueOnce({ content: '', bytes: 501 * 1024 * 1024, tooLarge: true })
    .mockResolvedValueOnce({ content: '# Approved large document', bytes: 501 * 1024 * 1024 })
  render(<ArtifactPreview artifact={artifact}/>)
  await screen.findByRole('heading', { name: 'Original small document' })
  fireEvent.click(screen.getByRole('button', { name: '刷新文件' }))
  await screen.findByRole('button', { name: '仍要打开' })
  expect(screen.queryByRole('heading', { name: 'Original small document' })).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: '仍要打开' }))
  await screen.findByRole('heading', { name: 'Approved large document' })
})

it('opens validated web addresses from an empty preview and rejects other schemes inline', () => {
  const onOpenUrl = vi.fn()
  render(<ArtifactPreviewEmpty onOpenUrl={onOpenUrl}/>)
  const input = screen.getByRole('textbox', { name: '输入网页 URL' })
  expect(screen.getByRole('button', { name: '打开网页预览' }).hasAttribute('disabled')).toBe(true)
  for (const url of ['javascript:alert(1)', 'file:///workspace/report.html', 'https://user:secret@example.com']) {
    fireEvent.change(input, { target: { value: url } })
    fireEvent.submit(input.closest('form')!)
    expect(screen.getByRole('alert').textContent).toContain('HTTP 或 HTTPS')
    expect(input.getAttribute('aria-invalid')).toBe('true')
  }
  expect(onOpenUrl).not.toHaveBeenCalled()
  fireEvent.change(input, { target: { value: '  https://example.com/报告  ' } })
  fireEvent.submit(input.closest('form')!)
  expect(onOpenUrl).toHaveBeenCalledWith('https://example.com/%E6%8A%A5%E5%91%8A')
  expect(screen.queryByRole('alert')).toBeNull()
  expect(bridge.readArtifact).not.toHaveBeenCalled()
})

it('reflects the current web URL in the address bar and resets it on file selection', () => {
  const onOpenUrl = vi.fn()
  const view = render(<ArtifactPreview artifact={{ ...artifact, path: undefined, url: 'https://example.com/report', kind: 'web' }} onOpenUrl={onOpenUrl}/>)
  expect((screen.getByRole('textbox', { name: '输入网页 URL' }) as HTMLInputElement).value).toBe('https://example.com/report')
  view.rerender(<ArtifactPreview artifact={{ ...artifact, path: undefined, content: '# Local document' }} onOpenUrl={onOpenUrl}/>)
  expect((screen.getByRole('textbox', { name: '输入网页 URL' }) as HTMLInputElement).value).toBe('')
})
