import { useState } from 'react'
import { ArrowLeft, Check, FileText, GitBranch, Play, Plus, Square, X } from 'lucide-react'
import { Button } from './ui/button'
import { Badge } from './ui/badge'
import { Input } from './ui/input'
import { Textarea } from './ui/textarea'
import { Label } from './ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from './ui/dialog'
import { Checkbox } from './ui/checkbox'
import { createStateEntry, proposeGoalState } from '@/lib/goals'
import { isTaskRunning, taskMutationLockReason, readySteps, reviewResult, setBusinessStatus, submitResult, taskStatusLabels, validatePlan } from '@/lib/workspace'
import type { AppState, Task } from '@/lib/types'
import type { ExecutionStep, TaskBusinessStatus } from '@/lib/task-types'

export function TaskOperations({task,state,onChange,onGoal,onSubtask,onRunStep,onOrchestrate,onTask,onEdit}:{task:Task;state:AppState;onChange:(fn:(s:AppState)=>AppState)=>Promise<void>;onGoal:(id:string)=>void;onSubtask:(parent:Task)=>void;onTask:(id:string)=>void;onEdit?:(trigger:HTMLButtonElement)=>void;onRunStep:(step:ExecutionStep)=>Promise<void>;onOrchestrate:(start:boolean)=>Promise<void>}) {
 const [tab,setTab]=useState('overview'),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const [summary,setSummary]=useState(''),[evidence,setEvidence]=useState(''),[resultRun,setResultRun]=useState('manual'),[reviewNote,setReviewNote]=useState('')
 const [stepOpen,setStepOpen]=useState(false),[stepTitle,setStepTitle]=useState(''),[instructions,setInstructions]=useState(''),[kind,setKind]=useState<'agent'|'human'>('agent'),[memberIds,setMemberIds]=useState<string[]>([]),[stepDeps,setStepDeps]=useState<string[]>([]),[expected,setExpected]=useState(''),[failure,setFailure]=useState<'halt'|'continue'>('halt')
 const goal=state.goals.find(g=>g.id===task.goalId),running=isTaskRunning(task),children=state.tasks.filter(t=>t.parentTaskId===task.id)
 const run=async(action:()=>Promise<void>)=>{if(busy)return;setBusy(true);setError('');try{await action()}catch(e){setError(String(e).replace('Error: ',''))}finally{setBusy(false)}}
 const mutate=(fn:(task:Task)=>Task)=>onChange(s=>({...s,tasks:s.tasks.map(t=>t.id===task.id?fn(t):t)}))
 const propose=(resultId:string)=>onChange(s=>{
   const current=s.tasks.find(t=>t.id===task.id)!,result=current.results?.find(r=>r.id===resultId),target=s.goals.find(g=>g.id===current.goalId)
   if(!result||!target)throw new Error('请先关联目标并提交结果')
   const source={kind:'task' as const,label:`任务结果：${current.title}`,taskId:current.id,runId:result.runId,reference:result.evidence}
   const next=proposeGoalState(target,{title:result.summary,entries:[createStateEntry(result.verdict==='accepted'?'artifact':'hypothesis',result.summary,source)],source,eventKey:`task-result:${result.id}`})
   return {...s,goals:s.goals.map(g=>g.id===target.id?next:g)}
 })
 const statuses={pending:'待执行',running:'执行中',review:'待确认',done:'已确认',failed:'失败 / 已停止',skipped:'已跳过'}
 return <div className="task-operations"><div className="task-context-strip"><Button variant="ghost" size="sm" disabled={!goal} onClick={()=>goal&&onGoal(goal.id)}><ArrowLeft size={12}/>{goal?.title||'独立任务'}</Button><Badge variant="outline">{taskStatusLabels[task.businessStatus??'todo']}</Badge><Button variant="ghost" size="sm" className="ml-auto" disabled={!onEdit||!!taskMutationLockReason(task)} title={taskMutationLockReason(task)||undefined} onClick={event=>onEdit?.(event.currentTarget)}>编辑任务</Button></div><div className="operations-tabs">{[['overview','任务与子任务'],['plan','执行编排'],['results',`结果与验收 ${task.results?.length||''}`]].map(([id,label])=><Button variant={tab===id?'secondary':'ghost'} size="sm" key={id} onClick={()=>setTab(id)}>{label}</Button>)}</div><div className="operations-body">{error&&<div role="alert" className="inline-error">{error}<Button variant="ghost" size="icon-sm" onClick={()=>setError('')} aria-label="关闭任务错误"><X/></Button></div>}
 {tab==='overview'&&<><div className="task-requirement"><span>验收要求</span><p>{task.acceptance||'尚未约定，可先记录希望交付的结果与检查方式。'}</p></div><div className="task-ops-row"><span>业务状态</span><Select value={task.businessStatus??'todo'} onValueChange={v=>void run(()=>mutate(t=>setBusinessStatus(t,v as TaskBusinessStatus)))}><SelectTrigger aria-label="任务业务状态"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(taskStatusLabels).map(([id,label])=><SelectItem value={id} key={id}>{label}</SelectItem>)}</SelectContent></Select><Button size="sm" variant="outline" onClick={()=>onSubtask(task)}><Plus size={12}/>子任务</Button></div>{(task.dependencies??[]).length>0&&<p className="ops-note">依赖：{task.dependencies!.map(id=>state.tasks.find(t=>t.id===id)?.title??'缺失任务').join('、')}。执行前检查是否已验收，不会自动启动依赖。</p>}{children.map(child=><div className="subtask-row" key={child.id}><GitBranch size={12}/><Button variant="link" onClick={()=>onTask(child.id)}>{child.title}</Button><Badge variant="outline">{taskStatusLabels[child.businessStatus??'todo']}</Badge></div>)}</>}
 {tab==='results'&&<><div className="result-form"><Label htmlFor="task-result-summary">结果说明</Label><Textarea id="task-result-summary" placeholder="交付了什么、发现了什么，或哪些假设被否定…" value={summary} onChange={e=>setSummary(e.target.value)}/><Input aria-label="结果依据" placeholder="产物路径、文档链接或验证记录" value={evidence} onChange={e=>setEvidence(e.target.value)}/><div className="task-ops-row"><Select value={resultRun} onValueChange={setResultRun}><SelectTrigger aria-label="关联执行"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="manual">用户提供 / 应用外完成</SelectItem>{task.runs.map((r,i)=><SelectItem key={r.id} value={r.id}>第 {i+1} 次执行</SelectItem>)}</SelectContent></Select><Button size="sm" disabled={busy||running||!summary.trim()} onClick={()=>void run(async()=>{await mutate(t=>submitResult(t,{summary,evidence,runId:resultRun==='manual'?undefined:resultRun}));setSummary('');setEvidence('')})}><FileText size={12}/>提交结果</Button></div></div>{!!task.results?.some(r=>r.verdict==='submitted')&&<Input aria-label="验收依据" placeholder="验收依据：如何确认满足要求，或为什么退回" value={reviewNote} onChange={e=>setReviewNote(e.target.value)}/>}<div className="result-list">{[...(task.results??[])].reverse().map(result=><article key={result.id}><div><Badge variant="outline">{{submitted:'待验收',accepted:'已验收',rejected:'已退回'}[result.verdict]}</Badge><time>{new Date(result.createdAt).toLocaleString('zh-CN')}</time></div><p>{result.summary}</p><small>{result.evidence||'尚未补充依据'}{result.runId?` · Run ${result.runId.slice(0,8)}`:''}</small>{result.reviewNote&&<p className="ops-note">验收记录：{result.reviewNote}</p>}<div className="task-ops-row">{result.verdict==='submitted'&&<><Button size="sm" variant="outline" disabled={busy||running} onClick={()=>void run(()=>mutate(t=>reviewResult(t,result.id,true,reviewNote)))}><Check size={12}/>验收通过</Button><Button size="sm" variant="ghost" disabled={busy||running} onClick={()=>void run(()=>mutate(t=>reviewResult(t,result.id,false,reviewNote)))}>退回</Button></>}{goal&&<Button size="sm" variant="ghost" disabled={busy||goal.proposals.some(p=>p.eventKey===`task-result:${result.id}`)} onClick={()=>void run(()=>propose(result.id))}>{goal.proposals.some(p=>p.eventKey===`task-result:${result.id}`)?'已提交目标变化':'提议更新现状'}</Button>}</div></article>)}</div></>}
 {tab==='plan'&&<><div className="task-ops-row"><span className="flex-1">{task.plan?.length??0} 个步骤 · 依赖完成后可执行</span><Button size="sm" variant="outline" disabled={running||task.orchestration==='running'} onClick={()=>{setStepTitle('');setInstructions('');setExpected('');setMemberIds(task.members.slice(0,1).map(m=>m.id));setStepDeps([]);setKind('agent');setStepOpen(true)}}><Plus size={12}/>步骤</Button>{task.orchestration==='running'?<Button size="sm" variant="outline" onClick={()=>void run(()=>onOrchestrate(false))}><Square size={12}/>停止编排</Button>:<Button size="sm" disabled={!task.plan?.some(s=>s.status==='pending')||running} onClick={()=>void run(()=>onOrchestrate(true))}><Play size={12}/>启动编排</Button>}</div><p className="ops-note">可并行步骤共用任务目录；应用运行时调度。Agent 步骤结束后等待确认，人工步骤需填写结果；失败按步骤策略处理。</p>{(task.plan??[]).map((step,i)=><article className="execution-step" key={step.id}><div><span className="step-order">{String(i+1).padStart(2,'0')}</span><strong>{step.title}</strong><Badge variant="outline">{statuses[step.status]}</Badge></div><p>{step.instructions}</p><small>{step.kind==='human'?'人工步骤':step.memberIds.map(id=>task.members.find(m=>m.id===id)?.name||'成员缺失').join('、')} · {step.dependsOn.length?`等待 ${step.dependsOn.map(id=>(task.plan??[]).find(s=>s.id===id)?.title).join('、')}`:'无前置依赖'} · 失败后{step.failurePolicy==='halt'?'停止后续':'允许继续'}</small>{step.expectedOutput&&<p className="ops-note">预期结果：{step.expectedOutput}</p>}<div className="task-ops-row">{step.status==='pending'&&step.kind==='agent'&&<Button size="sm" variant="outline" disabled={running||busy||!readySteps(task).some(s=>s.id===step.id)} onClick={()=>void run(()=>onRunStep(step))}><Play size={12}/>执行步骤</Button>}{(step.status==='review'||step.kind==='human'&&step.status==='pending')&&<><Input aria-label={`步骤结果 ${step.title}`} placeholder="填写确认依据或人工结果" value={step.output??''} onChange={e=>void mutate(t=>({...t,plan:t.plan?.map(s=>s.id===step.id?{...s,output:e.target.value}:s)})).catch(e=>setError(String(e)))}/><Button size="sm" variant="outline" disabled={!step.output?.trim()||!step.dependsOn.every(id=>task.plan?.some(s=>s.id===id&&(s.status==='done'||s.status==='failed'&&s.failurePolicy==='continue')))} onClick={()=>void run(()=>mutate(t=>({...t,plan:t.plan?.map(s=>s.id===step.id?{...s,status:'done'}:s)})))}><Check size={12}/>确认</Button></>}{step.status==='failed'&&<Button size="sm" variant="outline" disabled={running} onClick={()=>void run(()=>mutate(t=>({...t,plan:t.plan?.map(s=>s.id===step.id?{...s,status:'pending',runId:undefined}:s)})))}>重试步骤</Button>}{step.status==='pending'&&!running&&task.orchestration!=='running'&&<Button size="sm" variant="ghost" aria-label={`删除步骤 ${step.title}`} onClick={()=>void run(()=>mutate(t=>{if(t.plan?.some(s=>s.dependsOn.includes(step.id)))throw new Error('请先删除依赖该步骤的后续步骤');return {...t,plan:t.plan?.filter(s=>s.id!==step.id)}}))}><X size={12}/></Button>}</div></article>)}</>}
 </div><Dialog open={stepOpen} onOpenChange={setStepOpen}><DialogContent className="task-dialog"><DialogHeader><DialogTitle>新增执行步骤</DialogTitle><DialogDescription>选择成员、输入、依赖与预期输出；没有依赖的步骤可并行执行。</DialogDescription></DialogHeader><Label>步骤名称</Label><Input aria-label="步骤名称" value={stepTitle} onChange={e=>setStepTitle(e.target.value)}/><Label>执行指令</Label><Textarea aria-label="步骤指令" value={instructions} onChange={e=>setInstructions(e.target.value)}/><Select value={kind} onValueChange={v=>setKind(v as typeof kind)}><SelectTrigger aria-label="步骤类型"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="agent">Agent 执行</SelectItem><SelectItem value="human">人工确认 / 外部工作</SelectItem></SelectContent></Select>{kind==='agent'&&<div className="check-list">{task.members.map(m=><Label key={m.id}><Checkbox checked={memberIds.includes(m.id)} onCheckedChange={v=>setMemberIds(v?[...memberIds,m.id]:memberIds.filter(id=>id!==m.id))}/>{m.name} · {m.role}</Label>)}</div>}<Input aria-label="步骤预期输出" placeholder="预期输出 / 验证要求" value={expected} onChange={e=>setExpected(e.target.value)}/><Label>前置步骤</Label><div className="check-list">{(task.plan??[]).map(s=><Label key={s.id}><Checkbox checked={stepDeps.includes(s.id)} onCheckedChange={v=>setStepDeps(v?[...stepDeps,s.id]:stepDeps.filter(id=>id!==s.id))}/>{s.title}</Label>)}</div><Select value={failure} onValueChange={v=>setFailure(v as typeof failure)}><SelectTrigger aria-label="步骤失败策略"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="halt">失败后停止后续步骤</SelectItem><SelectItem value="continue">失败后仍允许后续步骤</SelectItem></SelectContent></Select>{error&&<p role="alert" className="text-destructive">{error}</p>}<DialogFooter><Button disabled={busy||!stepTitle.trim()} onClick={()=>void run(async()=>{await mutate(t=>{if(isTaskRunning(t)||t.orchestration==='running')throw new Error('运行时不能修改编排结构');const next={...t,plan:[...(t.plan??[]),{id:crypto.randomUUID(),title:stepTitle.trim(),instructions,kind,memberIds:kind==='human'?[]:memberIds,dependsOn:stepDeps,expectedOutput:expected,failurePolicy:failure,status:'pending' as const}]};validatePlan(next);return next});setStepOpen(false)})}>添加步骤</Button></DialogFooter></DialogContent></Dialog></div>
}
