import { chromium, expect } from '@playwright/test'
import { mkdir, writeFile } from 'node:fs/promises'

const output = 'test-results/sidebar'
await mkdir(output, { recursive: true })
const browser = await chromium.launch({ channel: 'chrome', headless: true })
const results = []
const title = '生成一篇如何做好业务品质的 html 文档并汇总所有验证结果与后续改进计划'
const goal = '持续提升业务品质并完善质量诊断自动化工作流与交付验收标准'
try {
  for (const [width, height] of [[1536, 960], [1280, 720]]) for (const reducedMotion of ['no-preference', 'reduce']) {
    const page = await browser.newPage({ viewport: { width, height }, reducedMotion })
    const errors = []
    page.on('pageerror', error => errors.push(error.message))
    await page.goto('http://127.0.0.1:1420')
    await page.getByRole('button', { name: '创建目标', exact: true }).first().click()
    await page.locator('#goal-title').fill(goal)
    await page.locator('#goal-expected').fill('完成品质文档')
    await page.getByRole('dialog').getByRole('button', { name: '创建目标', exact: true }).click()
    await page.getByRole('button', { name: '创建任务', exact: true }).click()
    await page.locator('#task-title').fill(title)
    await page.getByRole('dialog').getByRole('button', { name: '创建任务', exact: true }).click()
    await page.waitForFunction(() => !document.querySelector('[data-dialog-exit]'))
    await page.locator('[data-sonner-toast] [data-close-button]').click()
    await expect(page.locator('[data-sonner-toast]')).toHaveCount(0)
    const sidebar = page.getByRole('navigation', { name: '工作空间导航' })
    await expect(sidebar.getByRole('button', { name: '管理运行时', exact: true })).toHaveCount(0)
    const runtimeTrigger = sidebar.getByRole('button', { name: '展开 Runtime 与模型', exact: true })
    const runtimeHeader = sidebar.locator('.runtime-nav-header')
    await expect(runtimeHeader.locator('button')).toHaveCount(1)
    await runtimeTrigger.click()
    const runtimeCollapse = sidebar.getByRole('button', { name: '收起 Runtime 与模型', exact: true })
    await expect(runtimeCollapse).toBeVisible()
    await expect(sidebar.locator('.runtime-nav-item').first()).toBeVisible()
    await runtimeCollapse.click()
    await expect(sidebar.getByRole('button', { name: '展开 Runtime 与模型', exact: true })).toBeVisible()
    const handle = page.getByRole('separator', { name: '调整侧边栏宽度' })
    const size = async () => (await sidebar.boundingBox()).width
    const initial = await size()
    async function textFits() {
      const metrics = await sidebar.locator('.task-nav-item').first().evaluate(node => {
        const elements = [node.querySelector('.task-nav-top > span:last-child'), node.querySelector('.task-nav-bottom')]
        return elements.map(el => ({ width: el.clientWidth, scroll: el.scrollWidth, overflow: getComputedStyle(el).textOverflow, title: el.title, right: el.getBoundingClientRect().right, sidebarRight: el.closest('nav').getBoundingClientRect().right }))
      })
      for (const item of metrics) {
        expect(item.overflow).toBe('ellipsis')
        expect(item.scroll).toBeGreaterThan(item.width)
        expect(item.right).toBeLessThanOrEqual(item.sidebarRight)
        expect(item.title.length).toBeGreaterThan(20)
      }
    }
    await textFits()
    await page.screenshot({ path: `${output}/${width}-${reducedMotion}-narrow.png` })
    let box = await handle.boundingBox()
    const x = box.x + box.width / 2, y = box.y + box.height / 2
    await page.mouse.move(x, y)
    await expect(handle).toHaveAttribute('data-separator', 'hover')
    await page.mouse.down()
    await page.mouse.move(x + 110, y, { steps: 10 })
    expect(Math.abs(await size() - initial - 110)).toBeLessThan(2)
    await expect(handle).toHaveAttribute('data-separator', 'active')
    expect(await handle.evaluate(el => getComputedStyle(el).transitionDuration)).toBe('0s')
    await page.mouse.move(x + 45, y, { steps: 5 })
    expect(Math.abs(await size() - initial - 45)).toBeLessThan(2)
    await page.mouse.up()
    const released = await size()
    await page.mouse.move(x + 160, y)
    expect(await size()).toBeCloseTo(released, 0)
    await handle.focus()
    await page.keyboard.press('ArrowRight')
    expect(await size()).toBeGreaterThan(released)
    await page.keyboard.press('End')
    expect(await size()).toBeCloseTo(420, 0)
    await page.screenshot({ path: `${output}/${width}-${reducedMotion}-wide.png` })
    await page.keyboard.press('Home')
    expect(await size()).toBeCloseTo(200, 0)
    await page.keyboard.press('ArrowRight')
    const remembered = await size()
    await sidebar.getByRole('button', { name: '设置', exact: true }).click()
    await page.getByRole('button', { name: /返回工作台/ }).click()
    expect(await size()).toBeCloseTo(remembered, 0)
    // Real drag followed by a browser cancellation; moving with the button still
    // held must no longer resize the panel. Then verify the next drag works.
    box = await handle.boundingBox()
    await handle.evaluate(el => el.addEventListener('pointermove', event => { el.dataset.pointerId = String(event.pointerId) }))
    await page.mouse.move(box.x, y)
    await page.mouse.down()
    await page.mouse.move(box.x + 50, y, { steps: 5 })
    await handle.evaluate(el => el.dispatchEvent(new PointerEvent('pointercancel', { bubbles: true, pointerId: Number(el.dataset.pointerId), pointerType: 'mouse' })))
    const cancelled = await size()
    await page.mouse.move(box.x + 100, y, { steps: 5 })
    expect(await size()).toBeCloseTo(cancelled, 0)
    await expect(handle).not.toHaveAttribute('data-separator', 'active')
    await page.mouse.up()
    box = await handle.boundingBox()
    await page.mouse.move(box.x, y)
    await page.mouse.down()
    await page.mouse.move(box.x + 25, y, { steps: 4 })
    await page.mouse.up()
    expect(await size()).toBeCloseTo(cancelled + 25, 0)
    box = await handle.boundingBox()
    await page.mouse.move(box.x, y)
    await page.mouse.down()
    await page.mouse.move(box.x + 20, y, { steps: 4 })
    await page.evaluate(() => window.dispatchEvent(new Event('blur')))
    const blurred = await size()
    await page.mouse.move(box.x + 60, y, { steps: 4 })
    expect(await size()).toBeCloseTo(blurred, 0)
    await expect(handle).not.toHaveAttribute('data-separator', 'active')
    await page.mouse.up()
    await handle.focus()
    await page.keyboard.press('Home')
    await textFits()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(errors).toEqual([])
    results.push({ width, height, reducedMotion, initial, checks: ['runtime row has one disclosure control', 'long title and goal ellipsis', 'hover and active handle', '1:1 dragging and reversal', 'release', 'keyboard min/max', 'settings return retains width', 'pointer cancellation and subsequent drag', 'blur ends drag', 'viewport fits'], errors })
    await page.close()
  }
  await writeFile(`${output}/qa.json`, JSON.stringify(results, null, 2))
  console.log(JSON.stringify(results, null, 2))
} finally { await browser.close() }
