import { chromium, expect } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
await mkdir('test-results', { recursive: true })
const browser = await chromium.launch({ channel: 'chrome', headless: true })
const page = await browser.newPage({ viewport: { width: 1536, height: 960 } })
const errors = []
page.on('pageerror', e => errors.push(e.message))
try {
  await page.goto('http://127.0.0.1:1420')
  await expect(page.getByRole('heading', { name: '为工作台增加全局命令面板' })).toBeVisible()
  await page.screenshot({ path: 'test-results/workbench-1536.png' })
  await page.getByRole('button', { name: '设置', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Codex', exact: true })).toBeVisible()
  await page.locator('#runtime-name').fill('Codex 测试配置')
  await page.getByRole('button', { name: '执行默认值', exact: true }).click()
  await page.locator('#default-directory').fill('/tmp')
  await page.getByRole('button', { name: '运行时', exact: true }).click()
  await expect(page.locator('#runtime-name')).toHaveValue('Codex 测试配置')
  await page.getByRole('button', { name: '返回工作台' }).click()
  await expect(page.getByRole('dialog', { name: '放弃未保存的更改？' })).toBeVisible()
  await page.getByRole('button', { name: '继续编辑' }).click()
  await page.getByRole('button', { name: '模型与供应商', exact: true }).click()
  await page.getByRole('button', { name: '添加模型', exact: true }).first().click()
  await page.locator('#model-name').fill('本地配置的测试模型')
  await page.locator('#model-id').fill('fixture-model-v1')
  await page.locator('#model-runtime-codex').click()
  await page.getByRole('button', { name: '应用到配置', exact: true }).click()
  await page.getByRole('button', { name: '保存更改', exact: true }).click()
  await expect(page.getByText('所有更改已保存', { exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: '设置', exact: true }).click()
  await expect(page.locator('#runtime-name')).toHaveValue('Codex 测试配置')
  await page.screenshot({ path: 'test-results/settings-1536.png' })
  await page.setViewportSize({ width: 1280, height: 720 })
  await page.screenshot({ path: 'test-results/settings-1280.png' })
  await expect(page.getByRole('button', { name: '保存更改', exact: true })).toBeInViewport()
  await page.getByRole('button', { name: '返回工作台' }).click()
  await page.getByRole('button', { name: '新建任务', exact: true }).click()
  await page.locator('#task-title').fill('本地界面验收任务')
  await expect(page.locator('#task-directory')).toHaveValue('/tmp')
  await page.getByRole('button', { name: '创建任务', exact: true }).click()
  await expect(page.getByRole('heading', { name: '本地界面验收任务' })).toBeVisible()
  await page.getByRole('button', { name: /^消息接收者：/ }).click()
  await expect(page.getByRole('button', { name: '选择模型 本地配置的测试模型', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '选择模型 本地配置的测试模型', exact: true }).click()
  await page.keyboard.press('Escape')
  await page.getByRole('textbox', { name: '任务指令' }).fill('验证消息接收者和发送行为')
  await page.getByRole('button', { name: '发送指令', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('浏览器预览')
  await page.screenshot({ path: 'test-results/real-task-1280.png' })
  if (await page.getByRole('button', { name: '打开执行检查器', exact: true }).getAttribute('aria-pressed') === 'true') await page.getByRole('button', { name: '打开执行检查器', exact: true }).click()
  await page.getByRole('button', { name: '打开执行检查器', exact: true }).click()
  await expect(page.getByRole('complementary', { name: '执行检查器' })).toBeVisible()
  await expect(page.getByRole('button', { name: '收起检查器', exact: true })).toBeInViewport()
  await page.getByRole('button', { name: '收起检查器', exact: true }).click()
  await page.keyboard.press('Meta+k')
  await expect(page.getByRole('dialog', { name: '全局命令' })).toBeVisible()
  await page.keyboard.press('Escape')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.getByRole('button', { name: '协作', exact: true }).click()
  await expect(page.getByRole('button', { name: '协作', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: '单 Agent', exact: true }).click()
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth || document.documentElement.scrollHeight > innerHeight)
  if (overflow) throw new Error('Viewport overflow')
  if (errors.length) throw new Error(errors.join('\n'))
  console.log('PASS: task creation, model compatibility, settings drafts/save/reload, keyboard command, browser/native boundary, responsive panes, reduced motion; no page errors')
} finally { await browser.close() }
