import {chromium,expect} from '@playwright/test'
import {writeFile,mkdir} from 'node:fs/promises'
await mkdir('test-results/workspace-implementation',{recursive:true})
const browser=await chromium.launch({channel:'chrome',headless:true})
const results=[]
try{
for(const width of [1536,1280])for(const reducedMotion of ['no-preference','reduce']){
 const page=await browser.newPage({viewport:{width,height:width===1536?960:720},reducedMotion})
 const errors=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('http://127.0.0.1:1420')
 await page.getByRole('button',{name:'创建目标',exact:true}).first().click()
 await page.locator('#goal-title').fill('交付可试用的桌面工具')
 await page.locator('#goal-expected').fill('交付应用、完成验收并收集试用结果')
 await page.locator('#goal-criteria').fill('安装包可以启动\n核心流程通过验收')
 await page.locator('#goal-summary').fill('已有设计，尚未开始实现')
 await page.getByRole('dialog').getByRole('button',{name:'创建目标',exact:true}).click()
 await expect(page.getByRole('heading',{name:'交付可试用的桌面工具',exact:true})).toBeVisible()
 await page.waitForFunction(()=>!document.querySelector('[data-dialog-exit]'));
 await page.screenshot({path:`test-results/workspace-implementation/goals-${width}-${reducedMotion}.png`})
 await page.getByRole('button',{name:'创建任务',exact:true}).click()
 await page.locator('#task-title').fill('验证桌面工具安装与启动')
 await page.locator('#task-acceptance').fill('在干净目录启动并保留检查结果')
 await page.getByRole('combobox',{name:'新任务执行者'}).click()
 await page.getByRole('option',{name:'人工 / 应用外完成',exact:true}).click()
 await page.getByRole('dialog').getByRole('button',{name:'创建任务',exact:true}).click()
 await expect(page.getByRole('heading',{name:'验证桌面工具安装与启动'})).toBeVisible()
 await page.getByRole('tab',{name:'任务与编排'}).click()
 await page.getByRole('button',{name:/结果与验收/}).click()
 await page.getByLabel('结果说明').fill('安装包启动成功，完整流程检查已通过')
 await page.getByRole('textbox',{name:'结果依据',exact:true}).fill('/tmp/validation.md，安装与核心流程检查记录')
 await page.getByRole('button',{name:'提交结果',exact:true}).click()
 await page.getByRole('textbox',{name:'验收依据',exact:true}).fill('根据启动记录和逐项检查确认满足任务要求')
 await page.getByRole('button',{name:'验收通过',exact:true}).click()
 await expect(page.getByText('已验收',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'提议更新现状'}).click()
 await expect(page.getByRole('button',{name:'已提交目标变化'})).toBeDisabled()
 await page.screenshot({path:`test-results/workspace-implementation/task-${width}-${reducedMotion}.png`})
 await page.getByRole('navigation',{name:'工作空间导航'}).getByRole('button',{name:/^目标/}).first().click()
 const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('goalward.preview.v1')))
 expect(state.tasks[0].businessStatus).toBe('done')
 expect(state.goals[0].currentState.summary).toBe('已有设计，尚未开始实现')
 expect(state.goals[0].proposals).toHaveLength(1)
 await page.getByRole('button',{name:'核对变化',exact:true}).click()
 await page.getByRole('dialog').getByRole('button',{name:'采纳到现状',exact:true}).click()
 await expect.poll(async()=>page.evaluate(()=>JSON.parse(localStorage.getItem('goalward.preview.v1')).goals[0].currentState.entries.length)).toBe(1)
 await page.reload()
 await expect(page.getByRole('heading',{name:'交付可试用的桌面工具'})).toBeVisible()
 await page.getByRole('navigation',{name:'工作空间导航'}).getByRole('button',{name:/^任务/}).first().click()
 await expect(page.getByRole('heading',{name:'任务',exact:true})).toBeVisible()
 await page.screenshot({path:`test-results/workspace-implementation/tasks-${width}-${reducedMotion}.png`})
 await page.getByRole('navigation',{name:'工作空间导航'}).getByRole('button',{name:/运行中/}).click()
 await expect(page.getByText('当前没有运行中的 Agent')).toBeVisible()
 await page.getByRole('navigation',{name:'工作空间导航'}).getByRole('button',{name:/^Agents/}).click()
 await page.getByRole('button',{name:'新建 Agent',exact:true}).click()
 await page.locator('#new-agent-name').fill('探索助手')
 await page.locator('#new-agent-role').fill('调研与实验')
 await page.locator('#new-agent-instructions').fill('对候选方案做实验，保留依据，不提前下结论')
 await page.getByRole('dialog').getByRole('button',{name:'创建 Agent',exact:true}).click()
 await expect(page.getByRole('heading',{name:/探索助手/})).toBeVisible()
 await page.waitForFunction(()=>!document.querySelector('[data-dialog-exit]'))
 await page.screenshot({path:`test-results/workspace-implementation/agents-${width}-${reducedMotion}.png`})
 await page.getByRole('button',{name:'创建任务',exact:true}).click()
 await page.getByRole('button',{name:'继续配置任务'}).click()
 await page.locator('#task-title').fill('比较两种存储方案')
 await page.getByRole('dialog').getByRole('button',{name:'创建任务',exact:true}).click()
 await expect(page.getByRole('heading',{name:'比较两种存储方案'})).toBeVisible()
 const profileState=await page.evaluate(()=>JSON.parse(localStorage.getItem('goalward.preview.v1')))
 expect(profileState.tasks[0].goalId).toBeUndefined()
 expect(profileState.tasks[0].members[0].agentProfileId).toBe(profileState.agents[0].id)
 expect(profileState.tasks[0].members[0].instructions).toContain('保留依据')
 await page.getByRole('button',{name:'设置',exact:true}).click()
 await page.getByRole('button',{name:/Kimi CLI/}).first().click()
 await expect(page.getByRole('heading',{name:'Kimi CLI',exact:true})).toBeVisible()
 await page.screenshot({path:`test-results/workspace-implementation/settings-${width}-${reducedMotion}.png`})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 expect(errors).toEqual([])
 results.push({width,reducedMotion,passed:true,errors,checks:['goal creation','human task without runtime/directory','result submission and separate acceptance','pending proposal preserves state until accepted','source-linked goal change','reload persistence','task/running/settings navigation','Kimi settings visible','viewport fits','Agent profile to independent task with instruction snapshot']})
 await page.close()
}
await writeFile('test-results/workspace-implementation/qa.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results))
}finally{await browser.close()}
